examples: {}
examples_2: {}
examples_3: {}
fixOnlyOneTagName: false
operationIds: {}
operationTags: {}
renameTags: {}
requestSchemaNames: {}
responseDescriptions: {}
responseSchemaNames: {}
securityParameters: {}
validServerUrls:
  https://{vanity-name}.api.visier.io:
    url: https://{vanity-name}.api.visier.io
