#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: splitit-web-polling-v4-alpha
    type: cron
    env: node
    schedule: "*/30 * * * *"
    buildCommand: npm init -y; npm install konfig-cli
    repo: https://github.com/konfig-dev/splitit-web-sdks
    startCommand: ./node_modules/.bin/konfig pull && ./node_modules/.bin/konfig push -o konfig-dev -r splitit-web-sdks -s swagger.json
  - name: humanloop-polling-v4
    type: cron
    schedule: "*/30 * * * *"
    buildCommand: npm init -y; npm install konfig-cli
    env: node
    rootDir: v4
    repo: https://github.com/konfig-dev/humanloop-sdks
    startCommand: ./node_modules/.bin/konfig pull && ./node_modules/.bin/konfig push -o konfig-dev -r humanloop-sdks -s openapi.json -x v4
  - name: humanloop-polling-v4-alpha
    type: cron
    env: node
    schedule: "*/30 * * * *"
    buildCommand: npm init -y; npm install konfig-cli
    rootDir: v4-alpha
    repo: https://github.com/konfig-dev/humanloop-sdks
    startCommand: ./node_modules/.bin/konfig pull && ./node_modules/.bin/konfig push -o konfig-dev -r humanloop-sdks -s openapi.json -x v4-alpha

  - name: konfig-demo-product-landing-page
    type: web
    env: static
    buildCommand: yarn; yarn build; yarn next export
    staticPublishPath: ./out
    repo: https://github.com/konfig-dev/konfig
    rootDir: misc/konfig-demo-product-landing-page
    domains:
      - apidemo.konfigthis.com

  - name: konfig-demo-portal
    type: web
    env: node
    buildCommand: yarn; yarn build;
    startCommand: yarn start;
    repo: https://github.com/konfig-dev/konfig
    rootDir: generator/konfig-next-app
    domains:
      - demo.konfigthis.com
    envVars:
      - key: PYTHON_RCE_API_HOST_PORT
        fromService:
          name: konfig-python-remote-code-executor
          type: pserv
          property: hostport
      - fromGroup: github

  - name: konfig-dash
    type: web
    env: static
    buildCommand: yarn install && yarn build && yarn rw deploy render web
    staticPublishPath: ./web/dist
    repo: https://github.com/konfig-dev/konfig
    rootDir: generator/konfig-dash
    domains:
      - dash.konfigthis.com
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: SKIP_INSTALL_DEPS
        value: true
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        #####
        # NOTE: replace destination api url after first deploy to Render
        # example:
        #   destination: https://myredwoodproject-api.onrender.com/*
        #####
        destination: https://api.konfigthis.com/*
      - type: rewrite
        source: /*
        destination: /index.html

  - name: konfig-api
    type: web
    plan: starter
    env: node
    region: oregon
    repo: https://github.com/konfig-dev/konfig
    rootDir: generator/konfig-dash
    domains:
      - api.konfigthis.com
    buildCommand: yarn && yarn build && yarn rw build api
    startCommand: yarn rw deploy render api --prisma=false --data-migrate=false
    envVars:
      - fromGroup: aws
      - key: SESSION_SECRET
        generateValue: true
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: NODE_VERSION
        value: 16
      - key: DATABASE_URL
        fromDatabase:
          name: konfig-db
          property: connectionString
      - key: GENERATOR_API_HOST_PORT
        fromService:
          name: konfig-openapi-generator-api
          type: pserv
          property: hostport
      - key: BLACKD_API_HOST_PORT
        fromService:
          name: konfig-python-formatter
          type: pserv
          property: hostport
      - key: PYTHON_RCE_API_HOST_PORT
        fromService:
          name: konfig-python-remote-code-executor
          type: pserv
          property: hostport

  - type: pserv
    name: konfig-python-remote-code-executor
    env: python
    buildCommand: ./build-render.sh
    startCommand: ./start.sh
    repo: https://github.com/konfig-dev/konfig
    rootDir: generator/konfig-python-remote-code-executor
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000

  - type: pserv
    name: konfig-python-formatter
    env: python
    buildCommand: ./build-render.sh
    startCommand: ./start.sh
    repo: https://github.com/konfig-dev/konfig
    rootDir: generator/konfig-python-formatter-server-blackd

  - type: pserv
    name: konfig-openapi-generator-api
    env: docker
    rootDir: generator/konfig-generator-api
    repo: https://github.com/konfig-dev/konfig
    envVars:
      - fromGroup: aws
      - key: PORT
        value: 8080

  - type: web
    env: static
    name: konfig-docs
    rootDir: generator/konfig-docs
    buildCommand: yarn install; yarn build
    staticPublishPath: ./build
    repo: https://github.com/konfig-dev/konfig
    domains:
      - docs.konfigthis.com

databases:
  - name: konfig-db
    region: oregon
    plan: starter

envVarGroups:
  - name: aws
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
