removeOperationIdPrefix: true
additionalProperties:
  artifactId: snaptrade-java-sdk
  groupId: com.snaptrade
  invokerPackage: com.snaptrade.client
  modelPackage: com.snaptrade.client.model
  apiPackage: com.snaptrade.client.api
files:
  gitignore.mustache:
    destinationFilename: .gitignore
  Configuration.mustache:
    destinationFilename: src/main/java/com/snaptrade/client/Configuration.java
  ApiClient.mustache:
    destinationFilename: src/main/java/com/snaptrade/client/ApiClient.java
  build.gradle.mustache:
    destinationFilename: build.gradle
  JSON.mustache:
    destinationFilename: src/main/java/com/snaptrade/client/JSON.java
