openapi: 3.0.0
info:
  version: '1.0'
  title: Jobsoid API
tags:
  - name: Jobs
    description: API to fetch published jobs
  - name: Lookups
    description: API to fetch Lookups
paths:
  /api/v1/jobs:
    get:
      tags:
        - Jobs
      description: |
        Get a list of published jobs on your account
      parameters:
        - name: q
          in: query
          description: Search by Job Title (optional)
          schema:
            type: string
        - name: loc
          in: query
          description: Search by Location (optional)
          schema:
            type: integer
        - name: dept
          in: query
          description: Search by Department (optional)
          schema:
            type: integer
        - name: div
          in: query
          description: Search by Division (optional)
          schema:
            type: integer
        - name: fun
          in: query
          description: Search by Job Function (optional)
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
  /api/v1/jobs/{jobId}:
    parameters:
      - name: jobId
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Jobs
      description: |
        Get details of a Published Job
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
  /api/v1/locations:
    get:
      tags:
        - Lookups
      description: |
        Get a list of Locations on your account
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
  /api/v1/departments:
    get:
      tags:
        - Lookups
      description: |
        Get a list of Departments on your account
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
  /api/v1/divisions:
    get:
      tags:
        - Lookups
      description: >
        Get a list of Divisions on your account. Please contact support if you
        wish to enable this property on your account.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Division'
  /api/v1/functions:
    get:
      tags:
        - Lookups
      description: |
        Get a list of Job Functions on your account
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Function'
servers:
  - url: https://demo.jobsoid.com
components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: integer
          example: 1055
        code:
          type: string
          example: JOB-01
        title:
          type: string
          example: Software Developer
        description:
          type: string
        type:
          type: string
          example: Full Time
        positions:
          type: string
          example: 5
        experience:
          type: string
          example: 3 - 5 years
        salary:
          type: string
          example: $5000 - $7000
        industry:
          type: string
          example: Computer / Software
        location:
          $ref: '#/components/schemas/Location'
        department:
          $ref: '#/components/schemas/Department'
        division:
          $ref: '#/components/schemas/Division'
        function:
          $ref: '#/components/schemas/Function'
        postedDate:
          type: string
          format: date-time
        closingDate:
          type: string
          format: date-time
        hostedUrl:
          type: string
          example: https://demo.jobsoid.com/JobDetails/1055
        applyUrl:
          type: string
          example: https://demo.jobsoid.com/Apply/1055
    Location:
      type: object
      properties:
        id:
          type: integer
          example: 10030
        title:
          type: string
          example: US Head Office
        city:
          type: string
          example: Baltimore
        state:
          type: string
          example: MD
        country:
          type: string
          example: United States
        zip:
          type: string
          example: 21202
    Department:
      type: object
      properties:
        id:
          type: integer
          example: 2085
        title:
          type: string
          example: Software Development
    Division:
      type: object
      properties:
        id:
          type: integer
          example: 1055
        title:
          type: string
          example: Frontend Development
    Function:
      type: object
      properties:
        id:
          type: integer
          example: 102
        title:
          type: string
          example: Engineering
