additionalProperties:
  title: "OpenAPIGeneratorApi"
  invokerPackage: com.konfigthis.api
  configPackage: com.konfigthis.configuration
  basePackage: com.konfigthis
  apiPackage: com.konfigthis.api
  modelPackage: com.konfigthis.model
  artifactId: openapi-generator-api
  artifactDescription: API for OpenAPI Generator
  groupId: com.konfigthis
  developerEmail: dylan@konfigthis.com
  developerName: Konfig
  developerOrganization: konfigthis.com
  developerOrganizationUrl: https://konfigthis.com
  hideGenerationTimestamp: true
